const fs = require('fs');
let code = fs.readFileSync('src/components/Billing.tsx', 'utf8');

code = code.replace(
  "                  <table className=\"w-full text-sm text-left\">\n                    <thead>\n                      <tr style={{ backgroundColor: config.documentColor || '#f39c12', color: 'white' }}>\n                        <th className=\"py-3 px-4 align-middle font-bold uppercase text-[10px] tracking-wider w-16\">Numéro</th>\n                        <th className=\"py-3 px-4 align-middle font-bold uppercase text-[10px] tracking-wider\">Désignation</th>\n                        <th className=\"py-3 px-4 align-middle font-bold uppercase text-[10px] tracking-wider text-center\">Quantité</th>\n                        <th className=\"py-3 px-4 align-middle font-bold uppercase text-[10px] tracking-wider text-center\">Prix Unitaire</th>\n                        <th className=\"py-3 px-4 align-middle font-bold uppercase text-[10px] tracking-wider text-center\">Montant HT</th>\n                      </tr>\n                    </thead>\n                    <tbody>\n                      <tr className=\"border-b border-slate-200\">\n                        <td className=\"py-3 px-4 text-slate-600 align-middle\">-</td>\n                        <td className=\"py-3 px-4 font-bold text-slate-800 align-middle\">\n                          {store.products.find(p => p.id === selectedInvoice.productId)?.name || 'HUILE 2-40 5L'}\n                        </td>\n                        <td className=\"py-3 px-4 text-center font-mono align-middle\">{selectedInvoice.quantity}</td>\n                        <td className=\"py-3 px-4 text-center font-mono align-middle\">{selectedInvoice.pricePerLiter.toFixed(2)}</td>\n                        <td className=\"py-3 px-4 text-center font-mono font-bold align-middle\">{selectedInvoice.amountHT.toFixed(2)}</td>\n                      </tr>\n                    </tbody>\n                  </table>",
  "                  <table className=\"w-full text-sm text-left\">\n                    <thead>\n                      <tr style={{ backgroundColor: config.documentColor || '#f39c12', color: 'white' }}>\n                        <th className=\"py-3 px-4 align-middle font-bold uppercase text-[10px] tracking-wider w-16 text-center\">N°</th>\n                        <th className=\"py-3 px-4 align-middle font-bold uppercase text-[10px] tracking-wider\">Désignation</th>\n                        <th className=\"py-3 px-4 align-middle font-bold uppercase text-[10px] tracking-wider text-center\">Quantité</th>\n                        <th className=\"py-3 px-4 align-middle font-bold uppercase text-[10px] tracking-wider text-center\">Prix Unitaire</th>\n                        <th className=\"py-3 px-4 align-middle font-bold uppercase text-[10px] tracking-wider text-center\">Montant HT</th>\n                      </tr>\n                    </thead>\n                    <tbody>\n                      <tr className=\"border-b border-slate-200\">\n                        <td className=\"py-4 px-4 text-slate-600 align-middle text-center\">-</td>\n                        <td className=\"py-4 px-4 font-bold text-slate-800 align-middle\">\n                          {store.products.find(p => p.id === selectedInvoice.productId)?.name || 'Produit'}\n                        </td>\n                        <td className=\"py-4 px-4 text-center font-mono align-middle\">{selectedInvoice.quantity}</td>\n                        <td className=\"py-4 px-4 text-center font-mono align-middle\">{selectedInvoice.pricePerLiter.toFixed(2)}</td>\n                        <td className=\"py-4 px-4 text-center font-mono font-bold align-middle\">{selectedInvoice.amountHT.toFixed(2)}</td>\n                      </tr>\n                    </tbody>\n                  </table>"
);

fs.writeFileSync('src/components/Billing.tsx', code);
